version: '3.3'

services:
  quark:
    build: .
    image: ghcr.io/servercontainers/quark
    restart: always
    volumes:
      - ./data:/data
    ports:
      - "80:80"
    networks:
      - quark

networks:
  quark:
    driver: bridge
